// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxO8mdhOzD-Z_GcyBbQlIH9MP6IdCBbc4',
    appId: '1:853807174181:web:139b690bf044c3e759e5cc',
    messagingSenderId: '853807174181',
    projectId: 'ecom-8f47f',
    authDomain: 'ecom-8f47f.firebaseapp.com',
    storageBucket: 'ecom-8f47f.appspot.com',
    measurementId: 'G-VD683J5TQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBadjkAsSKzteWr6AiIHmOTPMWfX86m-zU',
    appId: '1:853807174181:android:f9aa1e64a600510b59e5cc',
    messagingSenderId: '853807174181',
    projectId: 'ecom-8f47f',
    storageBucket: 'ecom-8f47f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaBUZoY1TAa7EacFTpYQyKlTHqDaQK4M',
    appId: '1:853807174181:ios:02c6d01991e955cd59e5cc',
    messagingSenderId: '853807174181',
    projectId: 'ecom-8f47f',
    storageBucket: 'ecom-8f47f.appspot.com',
    iosClientId: '853807174181-4v9qnscckva4rksgiani50cr20hmftoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );
}
